### ISSUE TITLE
TARDIS entrance not connected to the shell / TARDIS does not recognize ice

### ISSUE THREAD

**Issue by WhoWarz** [WhoCraft/TardisRefined#135]
### Issue description

okay so i found these while recording a showcase for the mod. i was using immersive portals and im assuming that the door removing itself from the tardis was caused by that but the other issue was probably not. with issue 1 i attempted to exit the tardis and i was placed a few blocks next to the tardis. i had previosly messed with the coords so i assumed that was the issue. i closed the door and changed the direction and was proven correct. i ended up having to delete the world enterly due to this issue. issue 2 was discovered while trying to correct issue 1. the tardis "moved" and attempted to land on ice. it instead removed the ice and placed itself on the block below. im assuming it melted the ice which is a bit of a problem for lading. this issue happened to me again during the showcase. below i have a clip which i removed from my showcase (i included the initial door glitch but cut out the rest). the second instance of the ice is not included but the door thing is my main concern.

link: https://youtu.be/HWfyBznEBdA

### Steps to reproduce

link to video (same as above): https://youtu.be/HWfyBznEBdA

### Minecraft version

1.19.2 (Latest)

### Mod Loader Platform type

Fabric

### Mod Loader version

Fabric Loader Version 0.14.13-1.19.2

### Tardis Refined version

v1.0

**Comment by thejudge156** [comment]
For the portal, I think the issue is deeper than obvious, as the location used by the portal is based on the last known location, and since you landed it should have been set to where you had landed. The fact that the facing was changing in that variable makes me think that your TARDIS was kind of stuck in flight. I don't know how that happened but it would take a lot more research in the code to find. 

As for the ice, that should be an easy fix.

**Comment by thejudge156** [comment]
Me: Ice should be a easy fix
Also me 5 hours later: Pulling my hair out because wacky if logic
