### ISSUE TITLE
Terraformer isn't working and the shell doesn't work

### ISSUE THREAD

**Issue by mirek12328** [WhoCraft/TardisRefined#173]
### Issue description

in my survival world i started to make a tardis but when i placed the terraformer on the redstone block i did nothing and i have to run a command to get in the "Tardis"

### Minecraft version

1.19.2 (Latest)

### Mod Loader Platform type

Forge

### Mod Loader version

"Modrinth App"

### Tardis Refined version

v1.0

**Comment by Suff99** [comment]
We don't have a released version of Tardis Refined for 1.19.4

Are you using another other mods with the mod?

**Comment by mirek12328** [comment]
> We don't have a released version of Tardis Refined for 1.19.4
> 
> Are you using another other mods with the mod?

I use 1.19.2 but I couldn't select it when I created the problem report

**Comment by mirek12328** [comment]
> Are you using another other mods with the mod?

yes Immersive portals, JEI, Sodium, Shulker Box Tooltips, JourneyMap, fabric API but i did try to turn and uninstall some of them and that didn't do anything

**Comment by NuL1F3** [comment]
I am having this issue also, forge on 1.19.2

**Comment by TheRoborandy** [comment]
I'm having this exact issue now myself with the Terraformer.  Modlist provided.
![image](https://github.com/Suff99/TardisRefined/assets/154510818/cc6625b8-2ba3-41bd-8906-09a90d931096)

**Comment by Jeryn99** [comment]
Was this after placing it and leaving the world?

**Comment by TheRoborandy** [comment]
> Was this after placing it and leaving the world?

Details:

Upon first entry, I crashed out due to first generation taking too long (Description: Exception in server tick loop) (possibly something to do with the automatic doors mod I have that opens doors when I get close).
Upon reloading, I was in the freshly-grown TARDIS.
Placing down the copper and redstone, I placed the Terraformer, expecting it to flash and replace the copper and redstone structure.  However, it did not.
Deconstructing the structure, I exit the pack completely, thinking the crash did something to it.
Upon re-entering the pack, I attempt the structure again, to be met with another failure.
So I deconstruct once again, exit the TARDIS and restart the pack.
Upon restarting, I re-enter the TARDIS and try again, to be met with a third failure.

I have the initial crash log from first entry.

**Comment by Jeryn99** [comment]
I'm interested in that log

**Comment by TheRoborandy** [comment]
> I'm interested in that log

Coming right up.
[crash-2023-12-21_04.01.34-server.txt](https://github.com/Suff99/TardisRefined/files/13739969/crash-2023-12-21_04.01.34-server.txt)

**Comment by TheRoborandy** [comment]
Ok, did a somewhat-fix, since I'm guessing that first load-in screwed me over last time.  I exited before first generation, went in, and then broke no blocks, and it worked.
![image](https://github.com/Suff99/TardisRefined/assets/154510818/0fd5a0a7-f4d2-442d-affc-0c3dc101bbdd)
